### PR TITLE
Merge all 5 pull requests

### PR DESCRIPTION
**Pull request by NewCompte**
Issues:

* What should be circlejerk texture pack author?
* What should be sallaben's supreme texture pack author? There is no TagPro account with the name "sallaben".
* DaEvil1, poopants, MagicPigeon and whoever made that circlejerk texture pack should probably make a statement giving us the rights to use their images?

### CODE REVIEW

**Comment by DaEvil1** [comment]
I made all the textures in Mural, and I grant all permissions to Koalabeast. I think I've sent a couple of emails as well granting them as well.

**Comment by mcgrogan91** [comment]
Circlejerk author: Bizkut & Ion

Circlejerk Permissions: I grant koalabeast all rights to use all images in the circlejerk texture pack.  Ion does the same.

**Comment by theVDude** [comment]
Bah, I should've tossed in the [do what the fuck you want to public license](http://www.wtfpl.net/) in with my texture pack.

Have fun with terminalPX, I had fun making it! It belongs to you now!

**Comment by sallaben** [comment]
Supreme author: bicycle

**Comment by NewCompte** [comment]
Ok, we are only waiting on MagicPigeon to give consent. I have sent him a reddit PM.

By the way, have you seen that you can modify gravity wells now? Look at https://github.com/Nick-Riggs/tagpro-texture-packs/tree/master/flat for an example.

**Comment by sallaben** [comment]
Woah! Excellent. I will get right on that, but not tonight. :) sleepy!

**Comment by sallaben** [comment]
hey newcompte, just wondering: were you waiting for me to provide a gravity well texture or is that an optional part of the pack?

**Comment by NewCompte** [comment]
It's optional.

I am not waiting about that, but I am thinking about https://www.reddit.com/r/TagPro/comments/5g9ldo/suggestion_remove_or_improve_confusing_texture/

We might need a way to track texture pack popularity and order texture packs accordingly.

**Comment by theVDude** [comment]
I had been working on something like that for mod manager a while back, but felt weird collecting stats without asking. My idea had been to take the top 3 in use (reported by the script to me) and have those as "most popular" and then shuffle around the others a bit (so less popular ones would get seen at least.)

**Comment by sallaben** [comment]
My suggestion: have the first row be sorted by popularity (you can extend
this to the second row as well if 3 isn't enough). Have some kind of color
border or background that identifies these top 3. And have the rest in
alphabetical order.

**Comment by sallaben** [comment]
Any updates on this, NewCompte?

**Comment by NewCompte** [comment]
I will make the texture pack picker sortable. I was on holidays those past 3 weeks.

**Comment by NewCompte** [comment]
Ok I made it sortable, I am pushing this.

Sorry for the wait!

**Comment by NewCompte** [comment]
Here is how the sorting will look: Interface

**Comment by sallaben** [comment]
NewCompte is king! :^)

Thanks for being great!!!

**Pull request merged**
